### ISSUE TITLE
Episql vs. Sqlgg?

### ISSUE THREAD

**Issue by rgrinberg** [paurkedal/episql#1]
I'm evaluating a tool for generating OCaml code for generating CRUD code from a SQL schema and I've stumbled upon episql and [sqlgg](https://github.com/ygrek/sqlgg). I've noticed that you're a contributor to sqlgg so you obviously have experience with both tools so I'm very curious about your thoughts on this.

Thanks.

P.S. my database of choice is postgres and I'd like to avoid camlp4 so things like macaque are out of question.

**Comment by paurkedal** [comment]
You probably want to persistence-style generator that comes with epiSQL in that case.  My motivation for making it was that I originally used MaCaQue, but found myself spending too much effort on memory caching and coding simple operations like fetch and store.  Thus, I decided to make something that covers this common case and deals with caching, which is feasible given the restriction.  It does generate a select function for each table, but if you want general queries, including joins, you'll need to code it yourself, and if you do manually coded updates, you must call the `clear_select_cache` method which I just introduced.

So, if you need the memory-caching and don't need complex queries most of the time, it could save you a lot of work.  I think of it as a rather practical solution in that sense, which I use in one production code at the moment, more than an elegant solution.  On other hand, when more complex queries are needed, I use Caqti directly, which means writing query string without compile-time checking.

I think MaCaQue has a nice interface of one accepts the camlp4, though I was a bit weary when seeing the use of `Obj.magic` internally (as I wanted to make a Caqti backend for it).  I have been sketching a bit on plain-ocaml query-construction with type-checking, but didn't find a satisfying design yet.  The main issue is that it's not possible, as far as I can tell, to provide named tuples without a syntax extension, and unnamed tuples don't scale well to big tables.

**Comment by rgrinberg** [comment]
Thanks for the information. You haven't mentioned sqlgg though, is it similar enough in scope to epiSQL for a quick comparison?

Also, I don't think caching will be helpful for me at the moment. I will be mostly just populating my database in the near future and the querying will be mostly ad-hoc.

**Comment by paurkedal** [comment]
I haven't used sqlgg for any real project, so I'm maybe not the one to ask.  My impression though is that it's simple to use and provides more flexible queries without going around it, though the SQL parser and type checker is limited.  epiSQL is quite extensive when it comes to parsing PostgreSQL table definitions.  It does not parse other queries, but creates some pre-defined ones based on the table definitions.
