### ISSUE TITLE
ExtUnitSpecific.sysconf not available on OSX

### ISSUE THREAD

**Issue by rgrinberg** [paurkedal/episql#5]
Which unfortunately makes the following line fail:

https://github.com/paurkedal/episql/blob/master/lib/caqti_persist.ml#L45

Would be great if it was possible to do this in a cross platform way.

**Comment by paurkedal** [comment]
According to [Xcode man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/sysconf.3.html), OS X has the `sysconf` function and the `_SC_CLK_TCK` constant, so maybe it could be added to extunix?

@ygrek Could you comment?

**Comment by ygrek** [comment]
extunix configure log would help. I guess OSX is missing `_SC_AVPHYS_PAGES` which makes extunix disable this feature as a whole.

**Comment by paurkedal** [comment]
Thanks @ygrek, I believe @rgrinberg can help out with the configure log.

**Comment by rgrinberg** [comment]
Sure. Posted this in the extunix issue.

**Comment by ygrek** [comment]
fixed in extunix 0.1.3 soon to hit opam https://github.com/ocaml/opam-repository/pull/5177

**Comment by paurkedal** [comment]
Thanks!
